sudo: required

language: nodejs

services:
    - docker

before_install:
    - ./prepare.sh -t
    - docker-compose -f docker-compose.tests.yml up -d

script:
    - cd tests && npm test && cd ..

after_success:
    - ./build-coverage.sh --send

after_failure:
    - docker-compose logs lupus-users lupus-history lupus-game
