sudo: required

language: nodejs

services:
    - docker

before_install:
    - ./prepare.sh -t
    - docker-compose up -d

script:
    - cd tests && npm test && cd ..

after_failure:
    - docker-compose logs