version: '2'
services:
    lupus-users:
        build: ./lupus-users
        volumes:
            - ./lupus-users:/app
        environment:
            DEBUG: lupus-users:*
        stdin_open: true
        tty: true
        depends_on:
            - mongo
            - redis

    proxy:
        build: ./lupus-proxy
        ports:
            - "3000:80"
        depends_on:
            - lupus-users

    mongo:
        image: mongo

    redis:
        image: redis
