version: '2'
services:
    lupus-users:
        build: ./lupus-users
        volumes:
            - ./lupus-users:/app
        environment:
            DEBUG: lupus-users:*
        stdin_open: true
        tty: true
        depends_on:
            - mongo
            - redis

    lupus-history:
        build: ./lupus-history
        volumes:
            - ./lupus-history:/app
        environment:
            DEBUG: lupus-history:*
        stdin_open: true
        tty: true
        depends_on:
            - mongo
            - redis

    lupus-game:
        build: ./lupus-game
        volumes:
            - ./lupus-game:/app
        environment:
            DEBUG: lupus-game:*
        stdin_open: true
        tty: true
        depends_on:
            - mongo
            - redis

    proxy:
        build: ./lupus-proxy
        volumes:
            - ./lupus-frontend:/app
        ports:
            - "3000:80"
        depends_on:
            - lupus-users
            - lupus-history
            - lupus-game

    mongo:
        image: mongo

    redis:
        image: redis
