FORMAT: 1A
HOST: https://api-game.lupus.com/

# lupus-game

The game microservice of Lupus in Tabula. This manages all the actions for the game.

## Game logic [/game/socket.io/]

### Require the socket [GET]

Require a connection to a new websocket where all the requests are made

+ Response 101

+ Response 400 (application/json)
    + Attributes (Error)

## Data Structures
### Error
+ error: There was an error (string, required) - The error message
